#pragma once
#include <wx/defs.h>

enum {
    ID_TOOL_SELECT = wxID_HIGHEST + 200,
    ID_TOOL_RECT,
    ID_TOOL_CIRCLE,
    ID_TOOL_TEXT,
    ID_TOOL_BEZIER,
    ID_PALETTE_IMPORT,
    ID_PALETTE_EXPORT,
    ID_ASSET_ADD,
    ID_ASSET_REMOVE,
    ID_ASSET_RENAME,
    ID_HIER_TOGGLE_VISIBLE,
    ID_HIER_TOGGLE_LOCKED,
    ID_HIER_RENAME,
};
